#cloud-config
datasource:
  GCE:
    sec_between_retries: 5

# runcmd:
#   - [ bash, -lc, "mkdir -p /etc/motd.d && ln -sf /dev/null /etc/motd.d/50-default" ]

# write_files:
#   - path: /etc/motd.d/99-custom-google-cloud
#     owner: root:root
#     permissions: "0644"
#     defer: true
#     content: |
#       HELLO FROM CORE ON GOOGLE CLOUD!